### ISSUE TITLE
"calculating" note or icon

### ISSUE THREAD

**Issue by LyraSwift** [JacksonWages/z-Issues#6]
When the "Get Estimate" is pressed for large lists, it can sometimes be slow to calculate and retrieve the quote. It might be an idea to have a status icon or a "calculating" text appear between when the button is pressed and the data is displayed.

**Comment by JacksonWages** [comment]
Good idea, I'll look into that one.

**Comment by JacksonWages** [comment]
There is now a "Loading..." note that pops up. I'll work on making it prettier in the future. Leaving this open for that.

**Comment by JacksonWages** [comment]
This now takes a lot less time. I think that the "Loading..." is sufficient now that load times are about 64x faster.
